input:
  module: TornadoRest
  module_parameters:
    path: /api
    port: 8888

output:
  - module: GenericRelayBoard
    relays:
      5: lamp
      6: uv_lamp
      4: window_up
      3: window_down
      2: window_switch_bypass
    module_parameters:
      serial:
        port: /dev/ttyS0
        baudrate: 9600
      board_size: 8
  - module: DummyOutput
    relays:
      0: DummyOutput0
      1: DummyOutput1
      2: DummyOutput2
      3: DummyOutput3
# future modules
#  - module: firmata
#    relays: !range 0,9 # map relays 0 .. 9 to this module
#    module_parameters: # refer to module documentation
#      serial:
#        port: /dev/ttyUSB0
#        baud_rate: 9600
#      digial_io_ports: !range 2,12
#  - module: raspberry_pi_io
#    relays: !range 10,19
#    module_parameters:
#      io_ports: !range 0,11

