input:
  module: TornadoRest
  module_parameters:
    port: 8888
    api:
      virtual_path: /api
    static:
      physical_path: static
      directory_index: index.html
output:
  - module: GenericRelayBoard
    relays:
      2: window_switch_bypass
      3: window_down
      4: window_up
      5: lamp
      6: uv_lamp
    module_parameters:
      serial:
        port: /dev/ttyS0
        baudrate: 9600
      board_size: 8
  - module: DummyOutput
    relays:
      0: DummyOutput0_0
      1: DummyOutput0_1
      2: DummyOutput0_2
      3: DummyOutput0_3
  - module: DummyOutput
    relays:
      4: DummyOutput1_4
      5: DummyOutput1_5
      6: DummyOutput1_6
      7: DummyOutput1_7
# future modules
#  - module: Firmata
#    relays:
#      # Digital/Analog input/output pin number to relay id mapping
#      1: arduino_lamp
#      2: arduino_fan
#      3: arduino_boiler
#    module_parameters:
#      serial:
#        port: /dev/ttyUSB0
#        baud_rate: 9600
#  - module: RaspberryPiGpio
#    relays:
#      # RPi GPIO number to relay id mapping
#      17: rpi_alarm
#      18: rpi_garage_door

